import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // The project is intentionally loosely typed (tsconfig strict: false).
      "@typescript-eslint/no-explicit-any": "warn",
      "react/no-unescaped-entities": "warn",
      // Legacy data-fetching pattern used across the app; advisory only.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
  globalIgnores([
    "node_modules/**",
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by serwist at build time.
    "public/sw*.js",
    "public/swe-worker*.js",
    // Standalone OCR worker package (own package.json, ts-node style).
    "scripts/**",
  ]),
]);

export default eslintConfig;