'use client';
import { jsPDF } from 'jspdf';
import type { GoroboOrderJson, WalletSummary, WalletTransaction } from './gorobo-api';

// A4 portrait: height > width. A4 landscape: width > height.
// Standard fonts are WinAnsi - the ₹ glyph and Unicode minus/dashes are not available, so PDFs use ASCII ("Rs.", "-").
const PORTRAIT_W = 595.28;  // A4 portrait width in points
const PORTRAIT_H = 841.89;  // A4 portrait height in points
const LANDSCAPE_W = 841.89;  // A4 landscape width in points
const LANDSCAPE_H = 595.28;  // A4 landscape height in points
const MARGIN = 40;
const PORTRAIT_CONTENT_W = PORTRAIT_W - MARGIN * 2;
const LANDSCAPE_CONTENT_W = LANDSCAPE_W - MARGIN * 2;
const ACCENT: [number, number, number] = [245, 108, 66];
const DARK: [number, number, number] = [24, 24, 27];
const MUTED: [number, number, number] = [110, 108, 118];
const LIGHT: [number, number, number] = [244, 243, 246];

const rs = (v: number) => `Rs. ${Number(v || 0).toLocaleString("en-IN", { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`;

interface Col {
  label: string;
  width: number;
  align?: 'left' | 'right' | 'center';
}

interface PdfPageState {
  doc: jsPDF;
  y: number;
  footerLabel: string;
  page: number;
  pageWidth: number;
  pageHeight: number;
}

function newPage(state: PdfPageState) {
  state.doc.addPage();
  state.page++;
  state.y = MARGIN + 20;
  drawFooter(state);
}

function ensureSpace(state: PdfPageState, needed: number) {
  if (state.y + needed > state.pageHeight - 60) newPage(state);
}

function drawFooter(state: PdfPageState) {
  const { doc, y: _y, footerLabel, page, pageWidth, pageHeight } = state;
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(`Generated by AmazeCC Admin | GoRoBo | ${footerLabel}`, MARGIN, pageHeight - 30);
  doc.text(`Page ${page}`, pageWidth - MARGIN, pageHeight - 30, { align: 'right' });
}

function drawHeader(state: PdfPageState, title: string, subtitle: string) {
  const { doc, pageWidth, pageHeight } = state;
  doc.setFillColor(...DARK);
  doc.rect(0, 0, pageWidth, 64, 'F');
  doc.setFillColor(...ACCENT);
  doc.rect(0, 64, pageWidth, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN, 28);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(220, 220, 225);
  doc.text(subtitle, MARGIN, 44);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text(new Date().toLocaleString("en-IN"), pageWidth - MARGIN, 28, { align: 'right' });
  state.y = 88;
  drawFooter(state);
}

function drawTable(
  state: PdfPageState,
  cols: Col[],
  rows: (string | number)[][],
  opts: { headerFill?: [number, number, number]; totalsRow?: boolean } = {}
) {
  const { doc, pageWidth } = state;
  const rowH = 22;
  const headerH = 24;
  const pad = 6;

  ensureSpace(state, headerH + rowH);
  const startX = MARGIN;

  doc.setFillColor(...(opts.headerFill || LIGHT));
  doc.rect(startX, state.y, pageWidth - MARGIN * 2, headerH, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(...MUTED);
  let x = startX;
  cols.forEach((c) => {
    doc.text(c.label.toUpperCase(), x + pad, state.y + headerH - 8, { align: c.align === 'right' ? 'right' : 'left', maxWidth: c.width - 2 * pad });
    x += c.width;
  });
  state.y += headerH;

  rows.forEach((row, idx) => {
    if (idx % 2 === 1) {
      doc.setFillColor(...LIGHT);
      doc.rect(startX, state.y, pageWidth - MARGIN * 2, rowH, 'F');
    }
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...DARK);
    x = startX;
    cols.forEach((c, ci) => {
      const text = String(row[ci] ?? '');
      doc.text(text, x + pad, state.y + rowH - 8, { align: c.align === 'right' ? 'right' : 'left', maxWidth: c.width - 2 * pad });
      x += c.width;
    });
    state.y += rowH;
    if (state.y > state.pageHeight - 70) newPage(state);
  });

  doc.setDrawColor(230, 229, 232);
  doc.line(startX, state.y, startX + pageWidth - MARGIN * 2, state.y);
  state.y += 6;
}

function drawSummary(state: PdfPageState, rows: { label: string; value: string; bold?: boolean; big?: boolean }[]) {
  const { doc, pageWidth } = state;
  const rowH = 20;
  const width = 200;
  const x = pageWidth - MARGIN - width;

  rows.forEach((r) => {
    ensureSpace(state, rowH);
    doc.setFont('helvetica', r.bold ? 'bold' : 'normal');
    doc.setFontSize(r.big ? 12 : 9.5);
    doc.setTextColor(...(r.big ? ACCENT : DARK));
    doc.text(r.label, x, state.y + rowH - 7);
    doc.text(r.value, x + width, state.y + rowH - 7, { align: 'right' });
    state.y += rowH;
  });
}

export function downloadBomPdf(order: GoroboOrderJson, itemMap?: Map<string, string>) {
  const doc = new jsPDF({ unit: 'pt', format: [PORTRAIT_W, PORTRAIT_H] });
  const state: PdfPageState = { doc, y: 88, footerLabel: 'bill processor', page: 1, pageWidth: PORTRAIT_W, pageHeight: PORTRAIT_H };

  drawHeader(state, 'GoRoBo - Bill of Materials / Final Quote', `Order ${order.id.slice(0, 8)} | ${order.status.toUpperCase()}`);

  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(`Customer: ${order.userName}`, MARGIN, state.y);
  doc.text(`Phone: ${order.phoneNumber}`, MARGIN + 220, state.y);
  state.y += 16;
  doc.text(`Order placed: ${new Date(order.createdAt).toLocaleString("en-IN")}`, MARGIN, state.y);
  state.y += 24;

  const cols: Col[] = [
    { label: '#', width: 28, align: 'right' },
    { label: 'Product Name / Description', width: 280 },
    { label: 'Qty', width: 45, align: 'right' },
    { label: 'Unit (Rs.)', width: 80, align: 'right' },
    { label: 'Amount (Rs.)', width: 82, align: 'right' },
  ];

  const rows = order.items.map((line, i) => {
    let displayName = line.name && line.name.trim() ? line.name : '';
    if (!displayName && line.itemId && itemMap && itemMap.has(line.itemId)) {
      displayName = itemMap.get(line.itemId)!;
    }
    if (!displayName) {
      displayName = line.itemId || `Component #${i + 1}`;
    }

    return [
      i + 1,
      line.custom ? `${displayName} (custom)` : displayName,
      line.quantity,
      Number(line.unitPrice).toLocaleString("en-IN", { minimumFractionDigits: 2 }),
      (Number(line.unitPrice) * Number(line.quantity)).toLocaleString("en-IN", { minimumFractionDigits: 2 }),
    ];
  });

  drawTable(state, cols, rows);

  const summaryItems: { label: string; value: string; bold?: boolean; big?: boolean }[] = [
    { label: 'Subtotal', value: rs(order.subtotal) },
  ];

  if (Number(order.discountAmount) > 0) {
    summaryItems.push({
      label: `Discount (${order.discountPct}%)`,
      value: `- ${rs(order.discountAmount)}`,
    });
  }

  summaryItems.push(
    { label: 'Taxable', value: rs(order.taxable) },
    { label: `GST (${order.gstPct}%)`, value: `+ ${rs(order.gstAmount)}` },
    { label: 'Shipment', value: `+ ${rs(order.shipmentCost)}` },
    { label: 'Grand Total', value: rs(order.total), bold: true, big: true }
  );

  drawSummary(state, summaryItems);

  if (order.notes) {
    ensureSpace(state, 40);
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    doc.text('Notes:', MARGIN, state.y);
    doc.setTextColor(...DARK);
    doc.text(order.notes, MARGIN, state.y + 14, { maxWidth: PORTRAIT_CONTENT_W });
  }

  doc.save(`gorobo-bom-${order.id.slice(0, 8)}.pdf`);
}

export function downloadWalletPdf(summary: WalletSummary, transactions: WalletTransaction[]) {
  const doc = new jsPDF({ unit: 'pt', format: [LANDSCAPE_W, LANDSCAPE_H] });
  const state: PdfPageState = { doc, y: 88, footerLabel: 'amaze wallet', page: 1, pageWidth: LANDSCAPE_W, pageHeight: LANDSCAPE_H };

  drawHeader(state, 'Amaze Wallet - Transaction History', 'Profit, GST and vendor cost ledger for GoRoBo');

  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(`Exported: ${new Date().toLocaleString("en-IN")}`, MARGIN, state.y);
  state.y += 24;

  drawSummary(state, [
    { label: 'Profit (settled of total)', value: `${rs(summary.profitSettled)} of ${rs(summary.profitTotal)}` },
    { label: 'GST collected (settled of total)', value: `${rs(summary.gstSettled)} of ${rs(summary.gstTotal)}` },
    { label: 'Vendor cost paid (of payable)', value: `${rs(summary.vendorPaid)} of ${rs(summary.vendorPayable)}` },
    { label: 'Customer receipts (of receivable)', value: `${rs(summary.customerReceived)} of ${rs(summary.customerReceivable)}` },
  ]);
  state.y += 8;

  const cols: Col[] = [
    { label: 'Date', width: 100 },
    { label: 'Customer', width: 110 },
    { label: 'Profit', width: 75, align: 'right' },
    { label: 'GST', width: 70, align: 'right' },
    { label: 'Cost', width: 70, align: 'right' },
    { label: 'Customer Paid', width: 85, align: 'center' },
    { label: 'Vendor Paid', width: 75, align: 'center' },
  ];

  const rows = transactions.map((t) => [
    new Date(t.createdAt).toLocaleDateString("en-IN"),
    t.userName,
    t.customer.profit ? rs(t.customer.profit.amount) : '-',
    t.customer.gst ? rs(t.customer.gst.amount) : '-',
    t.vendor.cost ? rs(t.vendor.cost.amount) : '-',
    t.customer.profit?.status === 'settled' ? 'YES' : 'pending',
    t.vendor.cost?.status === 'settled' ? 'YES' : 'pending',
  ]);

  drawTable(state, cols, rows);

  const totals = [
    '',
    'TOTAL',
    rs(summary.profitTotal),
    rs(summary.gstTotal),
    rs(summary.vendorPayable),
    '',
    '',
  ];
  drawTable(state, cols, [totals], { totalsRow: true });

  doc.save(`gorobo-wallet-history-${new Date().toISOString().slice(0, 10)}.pdf`);
}
